name: Build and Push Docker Image

on:
  push:
    branches: [master]  # o la rama que uses

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clona el repo
        uses: actions/checkout@v3

      - name: Configura Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login a DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build y push a DockerHub
        uses: docker/build-push-action@v5
        with:
          context: ./Client
          file: ./Client/Dockerfile
          push: true
          tags: antonio1306/mi-app-react:latest


